### ISSUE TITLE
Ocarina of Time crashes when trying to launch hax by interacting with environment

### ISSUE THREAD

**Issue by artman41** [phase/oot3dhax_installer#8]
interacting with the bed in Link's house causes the game to crash

"An error has occurred, forcing the software to close."

"The system will now restart."

---

Screen appears to crash as designed to, but then the screen appears broken in all areas instead of just the left, then forcing the game to exit

**Comment by phase** [comment]
I'd try updating your 3DS. I don't know how well tested 9.9 is.

/cc @meladroit

**Comment by artman41** [comment]
I have hax 2.5 working through themehax, and the previous oot hax that meladroit compiled did work

and I'm pretty sure that if I update, I'll go to 10.2 haha

**Comment by phase** [comment]
You should _theoretically_ be able to install a 10.2 payload, update your 3DS to 10.2, and load the payload.

**Comment by artman41** [comment]
@phase can't, I'd need one of the following if I were to do that, and I have none:

---

Ironhax (requires IronFall 1.0 or IronFall 1.1. If you don't have them, you can't obtain them anymore).
Ninjhax (requires a physical copy of Cubic Ninja or Cubic Ninja ROM on Sky3DS).
OoThax (requires a copy of TLoZ: Ocarina of Time 3D and a save dongle).

**Comment by meladroit** [comment]
I don't have OoT3D available to test at the moment, and likely won't have it for the foreseeable future. I see no reason why 9.9 shouldn't work, though. I've only had the 'forcing the software to close' error happen after installing the wrong region save file.

A quick thing to try would be wiping your save data (back it up first!) and attempting the install again. If that doesn't work, try a manual install via svdt or save_manager. Rename the appropriate save0x.[region].bin file to save00.bin, download the appropriate otherapp payload from [here](http://smealum.github.io/3ds/#otherapp) and rename that to payload.bin, and just manually transfer those files into OoT3D save data.

If it's still broken, the problem is probably beyond me. If not, then we should probably do what [sploit_installer](https://github.com/smealum/sploit_installer) does now for payload name determination. In fact, we probably should be doing that anyway ...

If you have menuhax, I'd definitely recommend staying below 10.2. But technically, you should be able to update OoT3D with a 10.2 payload from *hax2.5 before updating to 10.2. Not advisable if you ask me (personally, there's no reason to update past 10.1, given that you can launch eShop through homebrew now).

**Comment by artman41** [comment]
@meladroit where should I put the otherapp payload? On the root? Or in the installer folder?

**Comment by meladroit** [comment]
Put both save00.bin and payload.bin on the SD card somewhere, and then transfer them to save data root using svdt (or save_manager, but I forget where you need to put the files to use that). If you're using svdt, you should be able to navigate to wherever you put the files on the SD card.

I've also pushed some changes to the git tree to defer payload determination to the server, so that you should basically be guaranteed to get the intended payload, but a manual install would still be a good test. If it works, then try the new binaries in the git tree and let us know if it's any better. If it doesn't work, then it's kind of out of our hands—we just maintain the installer, not the [actual exploit](https://github.com/yellows8/oot3dhax).

**Comment by artman41** [comment]
![scr_5_top_left](https://cloud.githubusercontent.com/assets/5568965/10867256/9d3b2e56-804f-11e5-8c45-69a53ef94ac2.png)
![scr_5_bottom](https://cloud.githubusercontent.com/assets/5568965/10867257/9d3b37c0-804f-11e5-88b7-9dfc47678262.png)
@meladroit new binaries didn't work, installing did though, trying the manual way now. I did find that on that attempt however, I could run _through_ the bed o-o

---

still not working, however I included a video of what happens when it crashes this time.
https://www.youtube.com/watch?v=8fTd1M_Tj6w

**Comment by meladroit** [comment]
I'm pretty sure this is an issue with oot3dhax itself rather than the installer at this point. Unfortunately that's something beyond our power to fix—something about the 9.9 payload must not be playing nice with the exploit (last time I checked, it works fine on N3DS 10.1.0-J). Closing accordingly.

**Comment by Committee** [comment]
I just press the ITEM button and the exploit loads.

**Comment by anthsalmo** [comment]
I have de same error when I try to start the oot3dHax 2.5 with a original cartbridge of the game, I have the 10.1.0-27u firmware

 "An error has occurred, forcing the software to close."

"The system will now restart."

The version 1.1 works and start the hombrew launcher, but it have a few problems with the new hombrew starter kit .

**Comment by artman41** [comment]
@anthsalmo, please add this to the current open issue
